EOS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
admin.autodiscover()

urlpatterns = patterns('EOS.homepage.views',
    url(r'^$', 'index', name='homepage_index'),
    url(r'^home/$', 'index', name='homepage_index'),
    url(r'^settings/$', 'settings', name='homepage_settings'),
    url(r'^manageUser/$', 'manageUser', name='homepage_manageUser'),
    url(r'^createPlant/$', 'createPlant', name='homepage_createPlant'),
    url(r'^addUserRight/$', 'addUserRight', name='homepage_addUserRight'),
    url(r'^Myfeedback/$', 'Myfeedback', name='homepage_feedback'),    
    url(r'^benchmark/$', 'benchmark', name='homepage_benchmark'),    
    url(r'^support/$', 'support', name='homepage_support'),    
    url(r'^plt/$', 'plantPage', name='homepage_plant'),
    url(r'^plt/(\w*)/$', 'plantPage', name='homepage_plant'),
    url(r'^plt/(\w*)/(\w*)/$', 'plantPage', name='homepage_plant'),
)

#urlpatterns += patterns('EOS.kpiEquations.views',
#    url(r'^kpiEqs/$', 'KpiEquations'),
#    url(r'^newKpiEq/$', 'NewKpiEquation'),
#)

urlpatterns += patterns('EOS.user_sys.views',
    url(r'^organisationpg/$', 'organisation_page', name='user_organisation_page'),
    url(r'^joinorga/$', 'join_organisation', name='user_join_organisation'),
    url(r'^askplant/$', 'ask_plant_right', name='user_ask_plant_right'),
    url(r'^request_page/$', 'request_page', name='user_request_page'),    
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
)

EOS/homepage/models.py
from django.db import models

# Create your models here.

EOS/kpiEquations/models.py
from django.db import models

# Create your models here.

EOS/homepage/forms.py
from django import forms

class ContactForm(forms.Form):
    """Form used in homepage/view.py in Myfeedback()"""
    email = forms.EmailField()
    information = forms.CharField(widget=forms.Textarea)
    problem = forms.CharField(widget=forms.Textarea)

class SupprUserRForm(forms.Form):
    """ """
    name = forms.CharField(max_length=100)
    plantName = forms.CharField(max_length=100)

class AddUserForm(forms.Form):
    """Form used in homepage/view.py in addUserRight()"""
    Aname = forms.CharField(max_length=100)
    AplantName = forms.CharField(max_length=100)

class AddNewPlant(forms.Form):
    """Form used in homepage/view.py in createPlant()"""
    p_name = forms.CharField(max_length=100, label="Plant name")

class PlantGraphParams(forms.Form):
    """Form used to specify the parameters for the Pland data visualisation"""
    SDate = forms.DateField(label="Start-date",
                            help_text="First day of the analized date range")
    EDate = forms.DateField(label="End-date",
                            help_text="Last day of the analized date range")
    IntervalType = forms.ChoiceField(label="Interval type",
                                     help_text="Select the resolution of the analized data",
                                     choices=[('day','Day'),
                                              ('week','Week'),
                                              ('month','Month')],
                                     initial='week')

EOS/kpiEquations/forms.py
from django.forms import ModelForm
from EOS.data_db.models import KpiEquations

class KpiEqForm(ModelForm):
    class Meta:
        model = KpiEquations

    def __init__(self, *args, **kwargs):
        super(KpiEqForm, self).__init__(*args, **kwargs)
        for fi in ['kpi_name','component_list','equation','constraints']:
            self.fields[fi].widget.attrs['cols'] = 80
            self.fields[fi].widget.attrs['rows'] = 1
        for fi in ['free_text','issues']:
            self.fields[fi].widget.attrs['cols'] = 80
            self.fields[fi].widget.attrs['rows'] = 3

EOS/user_sys/forms.py
from django import forms

class createOrganisation(forms.Form):
    Name = forms.CharField(max_length=50)

class joinOrganisationForm(forms.Form):
    """
    Form used in user_sys/view.py in join_organisation()
    """
    organisationEmail = forms.EmailField()

class requestPageForm(forms.Form):
    """
    Form used in user_sys/view.py in request_page()
    """
    val = forms.CharField(max_length=30)
    typ = forms.CharField(max_length=40)
    mess = forms.CharField(max_length=400, required=False)
    use = forms.CharField(max_length=50)

class changeSelectedForm(forms.Form):
    """
    Form used in user_sys/view.py in organisation_page()
    """
    name = forms.CharField(max_length=50)

class askPlantRightForm(forms.Form):
    """
    Form used in user_sys/view.py in ask_plant_right()
    """
    name = forms.CharField(max_length=50)

EOS/homepage/views.py
from django.shortcuts import render, render_to_response
from django.utils import simplejson
from django.contrib.auth.models import User
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Max
from django.db import connections

from EOS.user_sys.models import *
from EOS.request import *
from EOS.homepage.forms import *
from EOS.data_db.models import *
from EOS import settings as EOSSettings

#API that allow to create graphics
import gviz_api

from datetime import datetime

from registration_defaults.settings import *

@login_required()
def index(request):
    """
    View for the homepage
    """
    userName = request.user
    is_orga_manager = check_organisation_manager(userName)
    organisationName = get_organisation_name(userName)
    nbRequest = getNbRequest(is_orga_manager, userName)    
    selected = getSelectedPlant(userName)
    alSelected = checkIfSelectedPlant(selected)
    plants_list = get_plant_list(organisationName)
    dic = {'plants_list': plants_list,
           'organiName': organisationName,
           'is_orga_manager': is_orga_manager,
           'nbRequest': nbRequest,
           'selected': selected,
           'alSelected': alSelected,
           }
    return render(request, 'homepage/index.html', dic)

@login_required()
def manageUser(request):
    """
    view for the manage user part
    In this page we can just remove an user to a plant
    """

    userName = request.user
    is_user_authorized = check_organisation_manager(userName)
    Rlist = []
    organisationName = get_organisation_name(userName)
    MembreList = get_orga_user_list(userName, organisationName)
    PlantList = get_plant_list(organisationName)
    managerList = getOrgaManagerList (organisationName)
    for memb in MembreList:
        Rlist.append([memb, getPlantOrganisation(memb, organisationName)])

    if request.method == "POST":
        supForm = SupprUserRForm(request.POST)
        if supForm.is_valid():
            #Get info from the form and delete the user from the chosen plant
            name = supForm.cleaned_data['name']
            plantName = supForm.cleaned_data['plantName']            
            UserInPlant = getPlantOrganisation(name, organisationName)
            if plantName in UserInPlant:
                usr = User.objects.get(username__exact=name) #get user object   
                obj = plants.objects.filter(plants_name=plantName) #get plant object
                #Delete user in userlist of a plant / remove the relation
                obj[0].plants_member.remove(usr)
            return HttpResponseRedirect('')
    else:
        supForm = SupprUserRForm()
    return render_to_response('homepage/manageUser.html', {'is_user_authorized': is_user_authorized, 'managerList': managerList, 'MembreList': MembreList, 'PlantList': PlantList, 'supprForm': supForm, 'list': Rlist}, context_instance=RequestContext(request))

@login_required()
def addUserRight(request):
    """
    Same as manageUser but here we add an user to a plant.
    """

    userName = request.user
    organisationName = get_organisation_name(userName)
    MembreList = get_orga_user_list(userName, organisationName)
    PlantList = get_plant_list(organisationName)

    if request.method == 'POST':
        addForm = AddUserForm(request.POST)
        if addForm.is_valid():
            #Get info from the form and add the user in the plant.
            Aname = addForm.cleaned_data['Aname']
            AplantName = addForm.cleaned_data['AplantName']
            #Check the request
            UserInPlant = getPlant(Aname)            
            if AplantName in UserInPlant:
                #ToDo: add error mess to be reported
                pass
            else:
                usr = User.objects.get(username__exact=Aname)                
                obj = plants.objects.filter(plants_name=AplantName)
                obj[0].plants_member.add(usr)
            return HttpResponseRedirect('/manageUser/')
    else:
        addForm = AddUserForm()
    return render_to_response('homepage/addUserRight.html', {'MembreList': MembreList, 'PlantList': PlantList, 'addForm': addForm}, context_instance=RequestContext(request))

@login_required()
def Myfeedback(request):
    """
    Provisional funct
    Made to collect feedback
    """
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            success = True
            email = contact_form.cleaned_data['email']
            information = contact_form.cleaned_data['information']
            problem = contact_form.cleaned_data['problem']
            send_mail("EOS feedback",
                      "From : %s\n===================\n%s\n===================\n%s" % (email, information, problem), 
                      EOSSettings.MANAGERS[0][1],
                      ["georges.schutz@tudor.lu"]) #Currently the emails are send to my address. Need to be changed to an admin.
    else:
        contact_form = ContactForm()
    ctx = {'contact_form': contact_form}
    return render_to_response('homepage/Myfeedback.html', ctx, context_instance=RequestContext(request))

@login_required()
def createPlant(request):
    """
    Allows to create a new plant.
    """
    userName = request.user
    is_user_authorized = check_organisation_manager(userName)
    organisationName = get_organisation_name(userName)
    if request.method == "POST":
        nvPlant = AddNewPlant(request.POST)
        if nvPlant.is_valid():
            name = nvPlant.cleaned_data['p_name']            #Get the name of the new plant by the form
            obj = organisation.objects.filter(organisation_name=organisationName) #Get the object of the organisation of the connected user (manager)
            nPlant = plants(plants_name=name) #Create a new plant (object)
            nPlant.save()
            obj[0].plants_list.add(nPlant) #Link the new plant created to the selected organisation
            return HttpResponseRedirect('/home/')
    else:
        nvPlant = AddNewPlant()
    return render_to_response('homepage/createPlant.html', {'nvPlant':nvPlant, 'is_user_authorized': is_user_authorized}, context_instance=RequestContext(request))

@login_required()
def plantPage(request, plantNameReq=None, sectionSel='WWTP_Global'):
    """
    View of the plant page
    """

    #get some info on the connected user
    userName = request.user
    is_orga_manager = check_organisation_manager(userName)
    organisationName = get_organisation_name(userName)
    nbRequest = getNbRequest(is_orga_manager, userName)    
    selected = getSelectedPlant(userName)
    alSelected = checkIfSelectedPlant(selected)
    plantList = getPlant(userName)

    if is_orga_manager:
        plantList += get_plant_list(organisationName)
        plantList = list(set(plantList))

    if plantNameReq == None:
        plantNameURLReq = selected
    else:
        #Check the access right of the requested
        try:
            plantNameURLReq = plants.objects.get(plantKey = plantNameReq) #ToDo if url request is swiched to plantKey
        except plants.DoesNotExist:
            plantNameURLReq = None
    if plantNameURLReq == None or plantNameURLReq.plantKey not in plantList:
        #return an error page if the user has no access to the requested page
        return render(request, 'homepage/errorAccess.html',
                      { 'ReqPlantRef': plantNameReq, 
                        'selected': selected,} ) 

    ### Handle the Graph Parameter Form data
    if request.method == 'POST':
        PGPform = PlantGraphParams(request.POST)
        if PGPform.is_valid():
            request.session['PlantGraphParams'] = PGPform.cleaned_data
        else:
            pass #GScToDo: handle error in the posted data.
    elif request.session.get('PlantGraphParams',None):
        PGPform = PlantGraphParams(request.session['PlantGraphParams'])
    else:
        PGPinit = {'SDate':'2013-01-01', #ToDo use some thing usefull here
                   'EDate':'2013-11-01', #ToDo use latest data available for the plant (Week type)
                   'IntervalType':'week'}
        PGPform = PlantGraphParams(PGPinit)
        PGPValid = PGPform.is_valid()
        request.session['PlantGraphParams'] = PGPform.cleaned_data
    PGP = request.session['PlantGraphParams']

    ### Build the data selection depending on request
    lastupdate = None
    plantRef = plantNameURLReq.plantKey
    PlantKPi = Kpi.objects.filter(plant=plantRef)
    PlantParts = KpiParts.objects.filter(plant=plantRef)
    lastupdate = PlantKPi.filter(interval_type=PGP['IntervalType']).aggregate(Max('date'))['date__max']
    ### Get the KPIs to be represented
    kpiID = PlantKPi.distinct("kpi_id")
    if sectionSel == 'WWTP_Global':
        newKPi = kpiID.filter(kpi_id__regex="^KPI_WW(TP)*_")
    elif sectionSel == 'Mechanical_treatment_step':
        newKPi = kpiID.filter(kpi_id__regex=".*(SAND)")
    elif sectionSel == 'Biological_treatment_step':
        newKPi = kpiID.filter(kpi_id__regex=".*BIO")
    elif sectionSel == 'Further_treatment_steps':
        newKPi = None
    elif sectionSel == 'Energy_related_KPI':
        newKPi = kpiID.filter(kpi_id__regex=".*(ELW|ENERGY)")
    else:
        newKPi = None
    ### If any kpi, build the SQL request
    if newKPi:
        kpi = zip(*newKPi.values_list('kpi_id'))[0]
        #Build the crosstab query to get the data for the selected KPIs
        whereKPI = ' or '.join(["kpi_id = ''%s''"%ki for ki in kpi])
        asKPI = ', '.join(["%s float"%ki for ki in kpi])
        descL = [(ki,'number') for ki in kpi]
        sql = """SELECT * 
        FROM crosstab(
          'select date, kpi_id, value 
           from kpis 
           where (%(KPIWhere)s) AND interval_type = ''%(TimeRes)s''

EOS/kpiEquations/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.forms.models import modelformset_factory

from forms import KpiEqForm
from EOS.data_db.models import KpiEquations as KpiEq

def NewKpiEquation(request):
    if request.method == 'POST':
        form = KpiEqForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('')
    else:
        form = KpiEqForm()

    return render_to_response('NewKpiEquation.html', 
                  {'form': form,})
    
def KpiEquations(request):
    KpiEqFormSet = modelformset_factory(KpiEq,form=KpiEqForm)
    if request.method == 'POST':
        formset = KpiEqFormSet(request.POST)
        if formset.is_valid():
            return HttpResponseRedirect('')
    else:
        formset = KpiEqFormSet()

    return render_to_response('KpiEquations.html', 
                  {'formset': formset,})

EOS/templates/homepage/Myfeedback.html
{% extends "homepage/index.html" %}
{% block js %}

<script src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
<script>
	{% if user.is_authenticated %}
	$(document).ready(function () {
		txt = "Browser CodeName: " + navigator.appCodeName + "\n";
		txt+= "Browser Name: " + navigator.appName + "\n";
		txt+= "Browser Version: " + navigator.appVersion + "\n";
		txt+= "Cookies Enabled: " + navigator.cookieEnabled + "\n";
		txt+= "Platform: " + navigator.platform + "\n";
		txt+= "User-agent header: " + navigator.userAgent + "\n";
		txt+= "User-agent language: " + navigator.systemLanguage + "\n";
		$("#id_information").val(txt);
		email = "{{ user.email }}";
		$("#id_email").val(email);
		$("#id_information").attr("readonly", "readonly");
		$("#test").attr("align", "right");
		$("#id_problem").attr("placeholder", "Explain your problem");
		$("#id_problem").addClass("feed");
		$("#id_information").addClass("feed");
	});
	{% endif %}
</script>
{% endblock %}

{% block css %}
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" type="text/css" href="/static/global_style.css"/>
    <link rel="stylesheet" type="text/css" href="/static/menucss.css"/>
    <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap-responsive.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/bootstrap/js/bootstrap.min.js"/>
    <style src="/static/global_style.css"></style>
<style type="text/css">
	section {
	position: relative;
		margin-top: 290px;
	left: 400px;
	}
</style>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
	<div id="test"></div>
	<form action="." method="POST" class="well" id="feedback_block">
		{% csrf_token %}
		{{ contact_form.as_p }}
		<input type="submit" value="Send" class="span1">
	</form>
{% endif %}
{% endblock %}

EOS/templates/homepage/addUserRight.html
{% extends "homepage/index.html" %}

{% block path %}
<ul class="breadcrumb">
  <li><a href="{% url homepage_settings %}">Settings</a> <span class="divider">/</span></li>
  <li><a href="{% url homepage_manageUser %}">Manage users</a> <span class="divider">/</span></li>
  <li class="active">Add users rights</li>
</ul>
{% endblock %}

{% block js %}
{% if user.is_authenticated %}
<script src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
<script>
  //submit form with the selected plant and user
	function submitAddUser() {
		var user = $("#user_add").val(),
		plant = $("#plant_add").val();
		$("#id_Aname").val(user);
		$("#id_AplantName").val(plant);
		$('#addForm').submit();
	}
</script>
{% endif %}
{% endblock %}
{% block content %}
<div id="add_user" class="form-inline">
	<div id="add_user_form">
		<select id="user_add">
			{% for user in MembreList %}
			<option value="{{user}}">{{ user }}</option>
			{% endfor %}
		</select>
		<select id="plant_add">
			{% for pl in PlantList %}
			<option value="{{pl}}">{{ pl }}</option>
			{% endfor %}
		</select>
		<input type="button" value="Cancel" onclick="location.href='{% url homepage_manageUser %}'">
		<input type="button" value="Add" onclick="submitAddUser ()">
	</div>
</div>
<form id="addForm" action="." method="POST" style="display:none">
	{% csrf_token %}
	{{ addForm.as_table }}
	<input type="submit" value="Add">
</form>
{% endblock %}

EOS/templates/homepage/benchmark.html
{% extends "homepage/index.html" %}
{% block content %}
<div  class="well" >
  <h3>Benchmarking</h3>
  <p style="text-align: justify;">
    A benchmarking comparison tool based on Key Performance Indicators (KPIs) is implemented to enable anonymous cross border comparison of the participating plants. Apart from the classical benchmarking between plants EOS will focus on target- and best-practice values taken from literature. This enables the system to provide the operator with helpful information even at an early stage when only a few plants are connected to the system. Apart from this it enables plant operators to compare themselves to state of the art techniques. Those studies can be run on a regular basis. At the moment different (not comparable) benchmarking studies exist in different countries of the European Union (EU). They are usually performed once a year and plant operators often must pay for the participation. EOS enables the operator to take part in much more frequent studies specialised on energy efficiency for free. All they need to do is connect their plant to the system. A statistical tool is implemented for statistical validation of the data and for providing the operator with prepared trending graphs on a regular basis. The analysed and statistical edited data will be provided to the operator in an energy report. A set of KPIs was developed for data analysis. The KPIs address different levels of plant operation: From a global point of view, treatment step specific point of view down to aggregate specific analysis.
  </p>
</div>
<div class="container-fluid" style="position: relative; width:200%; left:-50px;"><!--left: -250px-->
  <div class="span8">
    <img class="img-polaroid" src="/static/img/stirrer.png" style="height: 400px; width: 660px"></img></div>
  <div class="span8">
    <img class="img-polaroid" src="/static/img/specific_energy.png" style="height: 400px; width: 800px;"></img></div>
</div>
{% endblock %}
{% block footer %}

{% endblock %}

EOS/templates/homepage/createPlant.html
{% extends "homepage/index.html" %}
{% block path %}
<ul class="breadcrumb">
  <li><a href="{% url homepage_settings %}">Settings</a> <span class="divider">/</span></li>
  <li class="active">Create plant</li>
</ul>
{% endblock %}

{% block js %}
{% endblock %}
{% block content %}

{% if user.is_authenticated %}
{% if not is_user_authorized %}
Access denied.
{% else %}

<div class="well" style="text-align:center;" >
<form class="form-inline" id="add_new_plant" action="." method="POST">
	{% csrf_token %}
	{{ nvPlant.as_table }}
	<input type="submit" value="Add">
</form>
</div>

{% endif %}
{% else %}
<p>Please <a href="{% url auth_login %}">log in</a>.</p>
{% endif %}

{% endblock %}

EOS/templates/homepage/errorAccess.html
{% extends "homepage/index.html" %}

{% block content %}
    <div style="text-align:center;" class="alert alert-error">
      <h4>{{ ReqPlantRef }}</h4>
      <p>You can't access to this plant.</p>
    </div>
{% endblock %}

EOS/templates/homepage/index.html
{% extends "base.html" %}

{% block js %}
    {{block.super}}
    <script src="/static/bootstrap/js/bootstrap-popover.js"></script>
{% endblock js %}

{% block path %}
{% endblock %}

{% block top_menu %}
   <nav id="top_menu">
      <table>
        <thead>
          <tr>
            <td><a href="{% url homepage_index %}">Home</a></td>
            <td><a href="{% url homepage_benchmark %}">Benchmark</a></td>
            <td><a href="{% url homepage_support %}">Decision support</a></td>
            {% if alSelected %}
            <td><a href="{% url homepage_plant selected.plantKey %}">Plant</a></td>
            {% else %}
            <td><a href="{% url user_organisation_page %}">Plant</a></td>
            {% endif %}
            <td><a href="{% url homepage_settings %}">Settings</a></td>
        </tr>
    </thead>
    </table>
  </nav>
{% endblock %}
{% block top_box %}
{% if user.is_authenticated %}
logged in as {{ user }}<br />
    {% if is_orga_manager %}
    <a href="{% url user_request_page %}">request ({{ nbRequest }})</a><br /><br /></br>
    {% endif %}
    Selected plant : {{ selected }} - <a href="{% url user_organisation_page %}">change</a>
    <br />
    <a href="{% url auth_logout %}">Logout</a><br />
{% else %}
    <a href="{% url auth_login %}">Login</a>
{% endif %}

{% endblock top_box %}
{% block content %}
<div class="well" style="text-align:center;">
  <h3>Welcome to the Energy Online System (EOS)</h3>
</div>
<!--<img src="/static/img/plantschema.jpg"></img>-->
<div class="well">
  <p>
    In the overall context of the INNERS project, an Energy Online System (EOS) has been developed as an aid to improve the energy efficiency of Waste Water Treatment Plants (WWTPs). Within the EOS, a number of tools have been developed (Benchmarking, Statistical Analysis and a Decision Support System, DSS) to assist a plant operator with improving plant efficiency. The EOS system is a collaboration of the Wupperverbandsgesellschaft für integrale Wasserwirtschaft, the University of Luxembourg and the Centre de Recherche Public Henri Tudor. However, all the INNERS partners have contributed to its completion.
  </p>
  <h4>INNERS Summary</h4>
  <p>
    Improving the energy balance of the urban water cycle is the aim of the INNERS project, which stands for “INNovative Energy Recovery Strategies in the urban water cycle”. Eleven partners from the Netherlands, United Kingdom, France, Germany, Belgium and Luxembourg are collaborating to think in a new way about the urban water cycle, not only as a system that transports water, but also as a potential source of energy. The partners in INNERS started a number of demonstration projects. These projects focus on energy recovery from different parts of the cycle, saving energy and promoting the reuse of this energy. The ambition of the researchers is high, they are striving for an energy-neutral or even an energy producing urban water cycle.
  </p>
  <h4>The urban water cycle as a source of energy</h4>
  <p>
    The urban water cycle is designed to transport water. Recent studies show that the water cycle includes a significant amount of energy, for example as heat. In the current situation that energy is not used and is lost. Moreover, it takes a lot of energy to transport and purify waste water from houses and industry. This can be illustrated by the following figures: municipal wastewater contains ten times the amount of energy required to treat wastewater in treatment plants. On average, only 20% of the energy input in wastewater treatment is recovered energy. This means currently we use only a small percentage of the available energy potential. INNERS aims to contribute to an energy-neutral or even an energy producing urban water cycle.
  </p>
  <h4>When and for who?</h4>
  <p>
    INNERS was launched in April 2011 and will run until December 2014. Target groups are technical students, technical specialists and policy makers.<br />
  </p>
</div>
{% endblock%}

EOS/templates/homepage/manageUser.html
{% extends "homepage/index.html" %}

{% block path %}
<ul class="breadcrumb">
  <li><a href="{% url homepage_settings %}">Settings</a> <span class="divider">/</span></li>
  <li class="active">Manage users</li>
</ul>
{% endblock %}


{% block js %}
<script>
	{% if user.is_authenticated %}
	$(document).ready(function () {
		$('.supprButton').each(function () {
			$(this).hide();
		});
		$('.lign').hover(function (){
			$('.lign').each(function () {
				$(this).find('.supprButton').hide();
			});
			var Mybutton = $(this).find('.supprButton');
			Mybutton.show();
		});
		
		$('.supprButton').click(function () {			
			var user = $(this).closest('table.table').find('.user');
			var plant = $(this).closest('td').find('.plant');
			$('#id_name').val(user.html());
			$('#id_plantName').val(plant.html());
			$('#supprForm').submit();
		});
	});
	{% endif %}
</script>
{% endblock %}

	{% block content %}
	{% if user.is_authenticated %}
	{% if not is_user_authorized %}
	Access denied.
	{% else %}
	<div class="well">		
		{% for memb, plantList in list %}
			<table class="table">				
					<thead>
						<tr>
							<th class='user'>{{ memb }}</th>
						</tr>
					</thead>
					<tbody>
						{% for plant in plantList %}
						<tr class='lign'>
							<td>
								<div class="plant">{{ plant }}</div>
								<div class="supprButton">
									<buttun class="btn btn-mini btn-inverse">Delete</button>
								</div>
							</td>
						</tr>
						{% endfor %}
					</tbody>					
				</table>			
				{% endfor %}
			<buttun class="btn" onclick="location.href='{% url homepage_addUserRight %}'" style="float: right;"><i class="icon-plus"></i> Add a plant to user</button>
		<form id="supprForm" action="." method="POST">
		{% csrf_token %}
		{{ supprForm.as_p }}
		<input type="submit" value="Delete">
	</form>
	</div>
	{% endif %}
	{% else %}
	<p>Please <a href="{% url auth_login %}">log in</a>.</p>
	{% endif %}
	{% endblock %}