EOS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
admin.autodiscover()

urlpatterns = patterns('EOS.homepage.views',
    url(r'^$', 'index', name='homepage_index'),
    url(r'^home/$', 'index', name='homepage_index'),
    url(r'^settings/$', 'settings', name='homepage_settings'),
    url(r'^manageUser/$', 'manageUser', name='homepage_manageUser'),
    url(r'^createPlant/$', 'createPlant', name='homepage_createPlant'),
    url(r'^addUserRight/$', 'addUserRight', name='homepage_addUserRight'),
    url(r'^Myfeedback/$', 'Myfeedback', name='homepage_feedback'),    
    url(r'^benchmark/$', 'benchmark', name='homepage_benchmark'),    
    url(r'^support/$', 'support', name='homepage_support'),    
    url(r'^plt/$', 'plantPage', name='homepage_plant'),
    url(r'^plt/(\w*)/$', 'plantPage', name='homepage_plant'),
    url(r'^plt/(\w*)/(\w*)/$', 'plantPage', name='homepage_plant'),
)

#urlpatterns += patterns('EOS.kpiEquations.views',
#    url(r'^kpiEqs/$', 'KpiEquations'),
#    url(r'^newKpiEq/$', 'NewKpiEquation'),
#)

urlpatterns += patterns('EOS.user_sys.views',
    url(r'^organisationpg/$', 'organisation_page', name='user_organisation_page'),
    url(r'^joinorga/$', 'join_organisation', name='user_join_organisation'),
    url(r'^askplant/$', 'ask_plant_right', name='user_ask_plant_right'),
    url(r'^request_page/$', 'request_page', name='user_request_page'),    
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
)

EOS/homepage/models.py
from django.db import models

# Create your models here.

EOS/kpiEquations/models.py
from django.db import models

# Create your models here.

EOS/homepage/forms.py
from django import forms

class ContactForm(forms.Form):
    """Form used in homepage/view.py in Myfeedback()"""
    email = forms.EmailField()
    information = forms.CharField(widget=forms.Textarea)
    problem = forms.CharField(widget=forms.Textarea)

class SupprUserRForm(forms.Form):
    """ """
    name = forms.CharField(max_length=100)
    plantName = forms.CharField(max_length=100)

class AddUserForm(forms.Form):
    """Form used in homepage/view.py in addUserRight()"""
    Aname = forms.CharField(max_length=100)
    AplantName = forms.CharField(max_length=100)

class AddNewPlant(forms.Form):
    """Form used in homepage/view.py in createPlant()"""
    p_name = forms.CharField(max_length=100, label="Plant name")

class PlantGraphParams(forms.Form):
    """Form used to specify the parameters for the Pland data visualisation"""
    SDate = forms.DateField(label="Start-date",
                            help_text="First day of the analized date range")
    EDate = forms.DateField(label="End-date",
                            help_text="Last day of the analized date range")
    IntervalType = forms.ChoiceField(label="Interval type",
                                     help_text="Select the resolution of the analized data",
                                     choices=[('day','Day'),
                                              ('week','Week'),
                                              ('month','Month')],
                                     initial='week')

EOS/kpiEquations/forms.py
from django.forms import ModelForm
from EOS.data_db.models import KpiEquations

class KpiEqForm(ModelForm):
    class Meta:
        model = KpiEquations

    def __init__(self, *args, **kwargs):
        super(KpiEqForm, self).__init__(*args, **kwargs)
        for fi in ['kpi_name','component_list','equation','constraints']:
            self.fields[fi].widget.attrs['cols'] = 80
            self.fields[fi].widget.attrs['rows'] = 1
        for fi in ['free_text','issues']:
            self.fields[fi].widget.attrs['cols'] = 80
            self.fields[fi].widget.attrs['rows'] = 3

EOS/user_sys/forms.py
from django import forms

class createOrganisation(forms.Form):
    Name = forms.CharField(max_length=50)

class joinOrganisationForm(forms.Form):
    """
    Form used in user_sys/view.py in join_organisation()
    """
    organisationEmail = forms.EmailField()

class requestPageForm(forms.Form):
    """
    Form used in user_sys/view.py in request_page()
    """
    val = forms.CharField(max_length=30)
    typ = forms.CharField(max_length=40)
    mess = forms.CharField(max_length=400, required=False)
    use = forms.CharField(max_length=50)

class changeSelectedForm(forms.Form):
    """
    Form used in user_sys/view.py in organisation_page()
    """
    name = forms.CharField(max_length=50)

class askPlantRightForm(forms.Form):
    """
    Form used in user_sys/view.py in ask_plant_right()
    """
    name = forms.CharField(max_length=50)

EOS/homepage/views.py
from django.shortcuts import render, render_to_response
from django.utils import simplejson
from django.contrib.auth.models import User
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Max
from django.db import connections

from EOS.user_sys.models import *
from EOS.request import *
from EOS.homepage.forms import *
from EOS.data_db.models import *
from EOS import settings as EOSSettings

#API that allow to create graphics
import gviz_api

from datetime import datetime

from registration_defaults.settings import *

@login_required()
def index(request):
    """
    View for the homepage
    """
    userName = request.user
    is_orga_manager = check_organisation_manager(userName)
    organisationName = get_organisation_name(userName)
    nbRequest = getNbRequest(is_orga_manager, userName)    
    selected = getSelectedPlant(userName)
    alSelected = checkIfSelectedPlant(selected)
    plants_list = get_plant_list(organisationName)
    dic = {'plants_list': plants_list,
           'organiName': organisationName,
           'is_orga_manager': is_orga_manager,
           'nbRequest': nbRequest,
           'selected': selected,
           'alSelected': alSelected,
           }
    return render(request, 'homepage/index.html', dic)

@login_required()
def manageUser(request):
    """
    view for the manage user part
    In this page we can just remove an user to a plant
    """

    userName = request.user
    is_user_authorized = check_organisation_manager(userName)
    Rlist = []
    organisationName = get_organisation_name(userName)
    MembreList = get_orga_user_list(userName, organisationName)
    PlantList = get_plant_list(organisationName)
    managerList = getOrgaManagerList (organisationName)
    for memb in MembreList:
        Rlist.append([memb, getPlantOrganisation(memb, organisationName)])

    if request.method == "POST":
        supForm = SupprUserRForm(request.POST)
        if supForm.is_valid():
            #Get info from the form and delete the user from the chosen plant
            name = supForm.cleaned_data['name']
            plantName = supForm.cleaned_data['plantName']            
            UserInPlant = getPlantOrganisation(name, organisationName)
            if plantName in UserInPlant:
                usr = User.objects.get(username__exact=name) #get user object   
                obj = plants.objects.filter(plants_name=plantName) #get plant object
                #Delete user in userlist of a plant / remove the relation
                obj[0].plants_member.remove(usr)
            return HttpResponseRedirect('')
    else:
        supForm = SupprUserRForm()
    return render_to_response('homepage/manageUser.html', {'is_user_authorized': is_user_authorized, 'managerList': managerList, 'MembreList': MembreList, 'PlantList': PlantList, 'supprForm': supForm, 'list': Rlist}, context_instance=RequestContext(request))

@login_required()
def addUserRight(request):
    """
    Same as manageUser but here we add an user to a plant.
    """

    userName = request.user
    organisationName = get_organisation_name(userName)
    MembreList = get_orga_user_list(userName, organisationName)
    PlantList = get_plant_list(organisationName)

    if request.method == 'POST':
        addForm = AddUserForm(request.POST)
        if addForm.is_valid():
            #Get info from the form and add the user in the plant.
            Aname = addForm.cleaned_data['Aname']
            AplantName = addForm.cleaned_data['AplantName']
            #Check the request
            UserInPlant = getPlant(Aname)            
            if AplantName in UserInPlant:
                #ToDo: add error mess to be reported
                pass
            else:
                usr = User.objects.get(username__exact=Aname)                
                obj = plants.objects.filter(plants_name=AplantName)
                obj[0].plants_member.add(usr)
            return HttpResponseRedirect('/manageUser/')
    else:
        addForm = AddUserForm()
    return render_to_response('homepage/addUserRight.html', {'MembreList': MembreList, 'PlantList': PlantList, 'addForm': addForm}, context_instance=RequestContext(request))

@login_required()
def Myfeedback(request):
    """
    Provisional funct
    Made to collect feedback
    """
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            success = True
            email = contact_form.cleaned_data['email']
            information = contact_form.cleaned_data['information']
            problem = contact_form.cleaned_data['problem']
            send_mail("EOS feedback",
                      "From : %s\n===================\n%s\n===================\n%s" % (email, information, problem), 
                      EOSSettings.MANAGERS[0][1],
                      ["georges.schutz@tudor.lu"]) #Currently the emails are send to my address. Need to be changed to an admin.
    else:
        contact_form = ContactForm()
    ctx = {'contact_form': contact_form}
    return render_to_response('homepage/Myfeedback.html', ctx, context_instance=RequestContext(request))

@login_required()
def createPlant(request):
    """
    Allows to create a new plant.
    """
    userName = request.user
    is_user_authorized = check_organisation_manager(userName)
    organisationName = get_organisation_name(userName)
    if request.method == "POST":
        nvPlant = AddNewPlant(request.POST)
        if nvPlant.is_valid():
            name = nvPlant.cleaned_data['p_name']            #Get the name of the new plant by the form
            obj = organisation.objects.filter(organisation_name=organisationName) #Get the object of the organisation of the connected user (manager)
            nPlant = plants(plants_name=name) #Create a new plant (object)
            nPlant.save()
            obj[0].plants_list.add(nPlant) #Link the new plant created to the selected organisation
            return HttpResponseRedirect('/home/')
    else:
        nvPlant = AddNewPlant()
    return render_to_response('homepage/createPlant.html', {'nvPlant':nvPlant, 'is_user_authorized': is_user_authorized}, context_instance=RequestContext(request))

@login_required()
def plantPage(request, plantNameReq=None, sectionSel='WWTP_Global'):
    """
    View of the plant page
    """

    #get some info on the connected user
    userName = request.user
    is_orga_manager = check_organisation_manager(userName)
    organisationName = get_organisation_name(userName)
    nbRequest = getNbRequest(is_orga_manager, userName)    
    selected = getSelectedPlant(userName)
    alSelected = checkIfSelectedPlant(selected)
    plantList = getPlant(userName)

    if is_orga_manager:
        plantList += get_plant_list(organisationName)
        plantList = list(set(plantList))

    if plantNameReq == None:
        plantNameURLReq = selected
    else:
        #Check the access right of the requested
        try:
            plantNameURLReq = plants.objects.get(plantKey = plantNameReq) #ToDo if url request is swiched to plantKey
        except plants.DoesNotExist:
            plantNameURLReq = None
    if plantNameURLReq == None or plantNameURLReq.plantKey not in plantList:
        #return an error page if the user has no access to the requested page
        return render(request, 'homepage/errorAccess.html',
                      { 'ReqPlantRef': plantNameReq, 
                        'selected': selected,} ) 

    ### Handle the Graph Parameter Form data
    if request.method == 'POST':
        PGPform = PlantGraphParams(request.POST)
        if PGPform.is_valid():
            request.session['PlantGraphParams'] = PGPform.cleaned_data
        else:
            pass #GScToDo: handle error in the posted data.
    elif request.session.get('PlantGraphParams',None):
        PGPform = PlantGraphParams(request.session['PlantGraphParams'])
    else:
        PGPinit = {'SDate':'2013-01-01', #ToDo use some thing usefull here
                   'EDate':'2013-11-01', #ToDo use latest data available for the plant (Week type)
                   'IntervalType':'week'}
        PGPform = PlantGraphParams(PGPinit)
        PGPValid = PGPform.is_valid()
        request.session['PlantGraphParams'] = PGPform.cleaned_data
    PGP = request.session['PlantGraphParams']

    ### Build the data selection depending on request
    lastupdate = None
    plantRef = plantNameURLReq.plantKey
    PlantKPi = Kpi.objects.filter(plant=plantRef)
    PlantParts = KpiParts.objects.filter(plant=plantRef)
    lastupdate = PlantKPi.filter(interval_type=PGP['IntervalType']).aggregate(Max('date'))['date__max']
    ### Get the KPIs to be represented
    kpiID = PlantKPi.distinct("kpi_id")
    if sectionSel == 'WWTP_Global':
        newKPi = kpiID.filter(kpi_id__regex="^KPI_WW(TP)*_")
    elif sectionSel == 'Mechanical_treatment_step':
        newKPi = kpiID.filter(kpi_id__regex=".*(SAND)")
    elif sectionSel == 'Biological_treatment_step':
        newKPi = kpiID.filter(kpi_id__regex=".*BIO")
    elif sectionSel == 'Further_treatment_steps':
        newKPi = None
    elif sectionSel == 'Energy_related_KPI':
        newKPi = kpiID.filter(kpi_id__regex=".*(ELW|ENERGY)")
    else:
        newKPi = None
    ### If any kpi, build the SQL request
    if newKPi:
        kpi = zip(*newKPi.values_list('kpi_id'))[0]
        #Build the crosstab query to get the data for the selected KPIs
        whereKPI = ' or '.join(["kpi_id = ''%s''"%ki for ki in kpi])
        asKPI = ', '.join(["%s float"%ki for ki in kpi])
        descL = [(ki,'number') for ki in kpi]
        sql = """SELECT * 
        FROM crosstab(
          'select date, kpi_id, value 
           from kpis 
           where (%(KPIWhere)s) AND interval_type = ''%(TimeRes)s''

EOS/kpiEquations/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.forms.models import modelformset_factory

from forms import KpiEqForm
from EOS.data_db.models import KpiEquations as KpiEq

def NewKpiEquation(request):
    if request.method == 'POST':
        form = KpiEqForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('')
    else:
        form = KpiEqForm()

    return render_to_response('NewKpiEquation.html', 
                  {'form': form,})
    
def KpiEquations(request):
    KpiEqFormSet = modelformset_factory(KpiEq,form=KpiEqForm)
    if request.method == 'POST':
        formset = KpiEqFormSet(request.POST)
        if formset.is_valid():
            return HttpResponseRedirect('')
    else:
        formset = KpiEqFormSet()

    return render_to_response('KpiEquations.html', 
                  {'formset': formset,})

EOS/templates/user_sys/ask_plant_right.html
{% extends "homepage/index.html" %}

{% block path %}
<ul class="breadcrumb">
  <li><a href="{% url homepage_settings %}">Settings</a> <span class="divider">/</span></li>
  <li class="active">Access plant</li>
</ul>
{% endblock %}


{% block js %}
<script>
	$(document).ready(function (){
		$("#select_submit").click(function(){
			$("#id_name").val($("#plant_select_form :selected").val());
			$('#askRight').submit();
		});
	});
</script>
{% endblock %}
{% block content %}	
{% if error %}
	<div class='alert alert-error'>{{ error }}</div>
	{% endif %}
<div class="well" style="margin-top:20px;">
	Ask for plant access : <br/>
	<div class="form-inline" style="text-align: center;">
	<select id="plant_select_form">		
		{% for plant in plantList %}
		<option id="{{ plant.plants_name }}" value="{{ plant.plants_name }}">{{ plant.plants_name }}</option>
		{% endfor %}		
	</select>
	<button class="btn" id="select_submit" >Select</button>
	</div>
	</div>
<div style="display:none;">
	<form id="askRight" class="form-inline" action="." method="POST">
		{% csrf_token %}
		{{ form.as_table }}
		<button type="submit" class="btn">Submit</button>
	</form>
</div>
{% endblock %}

EOS/templates/user_sys/join_organisation.html
{% extends "homepage/index.html" %}

{% block js %}
{% endblock %}
{% block path %}
<ul class="breadcrumb">
  <li><a href="{% url homepage_settings %}">Settings</a> <span class="divider">/</span></li>
  <li class="active">Join organisation</li>
</ul>
{% endblock %}

{% block content %}
	{% if error %}
	<div class='alert alert-error'>{{ error }}</div>
	{% endif %}
	<form id="add_new_plant" class="form-inline" action="." method="POST">
		{% csrf_token %}
		{{ form.as_table }}
		<button type="submit" class="btn">Submit</button>
	</form>
{% endblock %}

EOS/templates/user_sys/join_organisation_confirm.html
{% extends "homepage/index.html" %}

{% block content %}
	You successfully requested to join the organisation {{ orga }}.
{% endblock %}

EOS/templates/user_sys/organisation_page.html
{% extends "homepage/index.html" %}

{% block js %}
	{{block.super}}
	<script>
		$(document).ready(function (){
			if ('{{ selected }}' != "None") {
			selId = {{ selected }};
			$(selId).attr("selected", "selected");
			};
			$("#select_submit").click(function(){
				$("#id_name").val($("#select_form :selected").val());
				$('#changeSel').submit();
			});
		});
	</script>
{% endblock js %}
{% block content %}
{% if inOrga %}
<div class="well" style="margin-top:20px;">
	Selected plant : <br/>
	<div class="form-inline" style="text-align: center;">
	<select id="select_form">		
		{% for plant in plantList %}
		<option id="{{ plant.plants_name }}" value="{{ plant.plants_name }}">{{ plant.plants_name }}</option>
		{% endfor %}		
	</select>
	<button class="btn" id="select_submit" >Select</button>
	</div>
</div>
<div class="well" id="test_cache">	
	<table class="table">
		<caption>Plant</caption>
		<thead>
			<tr>
				<th>Plant's name</th>
				<th>Energy consumption</th>
				<th>Traffic light</th>
				<th>Self energy production</th>
			</tr>
		</thead>
		<tbody>
			{% for plant in plantList %}
			<tr>				
				<td>				
					<a href="{% url homepage_plant plant.plantKey %}">{{ plant.plants_name }}</a>
				</td>
				<td>--kWh/d</td>
				<td><i class="icon-warning-sign"></i></td>
				<td>--%</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
<div style="display:none">
	<form id="changeSel" action="." method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="change">
	</form>
</div>
{% else %}
<div class="alert alert-info">
You currently have no organisation. You can join an organisation by clicking : <a href="{% url user_join_organisation %}">here</a>.
</div>
{% endif %}
{% endblock %}

EOS/templates/user_sys/request_page.html
{% extends "homepage/index.html" %}

{% block js %}
	<script type="text/javascript" src="http://www.google.com/jsapi"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script>
	$(document).ready(function () {
		$('.appr').click(function () {
			$("#id_val").val($(this).html());
			$("#id_typ").val($(this).closest('tr').find('.rtype').html());
			$("#id_use").val($(this).closest('tr').find('.ruser').html());
			$("#id_mess").val($(this).closest('tr').find('.rmessage').html());
			$('#subRequest').submit();
		});
		$('.decl').click(function () {
			$("#id_val").val($(this).html());
			$("#id_typ").val($(this).closest('tr').find('.rtype').html());
			$("#id_use").val($(this).closest('tr').find('.ruser').html());
			$("#id_mess").val($(this).closest('tr').find('.rmessage').html());
			$('#subRequest').submit();
		});	
	});
	</script>
{% endblock %}

{% block content %}
	<h2 style="margin-bottom:20px;">Requests</h2>
	<table class="table">
		<tbody>
			{% for rtype, ruser, rmessage in requestList %}
			<tr>
				<td class="rtype">{{ rtype }}</td>
				<td class="ruser">{{ ruser }}</td>
				<td class="rmessage">{{ rmessage }}</td>
				<td><a class="appr" href="javascript:">Approve</a> - <a class="decl" href="javascript:">Decline</a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

<div style="display: none;">
	<form id="subRequest" class="form" action="."  method="POST">
		{% csrf_token %}
		{{ form.as_table }}
		<button type="submit" class="btn">Submit</button>
	</form>
</div>
{% endblock %}